### ISSUE TITLE
When importing there are a lot of error due to wrong module names or missing modules.

### ISSUE THREAD

**Issue by RCatersels** [mendix/MxPushNotifications#1]
Hello Simon,

Here my remariks from trying to incorporate the module. 

After importing I have a couple of errors I need to get rid of.

The module is looking for the Account entity in the module UserManagent but when creating a new project this module is called Administration and not UserManagement. Renaming the Administration module to UserManagement and back again solves the first couple of errors.

Encryption module is needed for the encryption part. This should be mentioned in the steps to take.

I am missing a couple of layouts: SidebarLayout , PhoneLayout. These layouts are not in the standard layouts that Mendix creates in the new Layouts module. Either change them to a layout from this module or incorporate the layout in the module. Could you give me a pointer on where to find these layouts? Or could you export these layouts so I can import them?

Step 2 components.json
Here you should eloborate a bit more for the non widget builders. I assume it is the file in the deployment/web folder. I have changed the line there to:
{"files":{"css":["lib/bootstrap/css/bootstrap.min.css","mxclientsystem/mxui/ui/mxui.css","css/theme.css"],"js":["mxclientsystem/mxui/mxui.js",'js/jquerymin.js","widgets/pushNotifications/lib/PushNotification.js"]},"cachebust":"635616037247518257"}

But I have no idear if this is right.

Hope to hear from you.

Regards,

Ronald

**Comment by simo101** [comment]
Thanks Ronald. I will update the information and the module. This feedback is very valuable to me. At the moment the module is still needs approval from the appstore team so its still in "Beta" effectively. The more feedback like this the better the module will be. The components file should go into the theme folder not the deployment folder. See the test project for an example.

**Comment by simo101** [comment]
I have updated the module to improve the dependencies and extended the readme file.
