### ISSUE TITLE
i dont get a device registration id

### ISSUE THREAD

**Issue by sladeaugustine** [mendix/MxPushNotifications#13]
Hi i am trying to implement this module for a project and got the gcm connection setup however when the ds microflow gets called and i use my mobile phone in hybrid mobile environment i dont get a registration id returned?

**Comment by simo101** [comment]
Have you wrapped up your application with phonegap or are you using the Mendix developer tool? If so the mendix developer tool will not work. You also have to be logged in as an account type of user.

**Comment by sladeaugustine** [comment]
Oh ok yes i was using mendix developer tool.

Thanks man. I will complete the phone gap as well and let you know. Thanks again mate
