### ISSUE TITLE
Limited to use with Phonegap?

### ISSUE THREAD

**Issue by ppoetsma** [mendix/MxPushNotifications#15]
Hi,

Is the use of this module limited to use with Phonegap? Can I use it to send push notifications to an app built with any other development platform?

Regards,
Paul

**Comment by pimvdnoll** [comment]
The module delivers just the message to the servers of apple/google/ms zo it can be any app. Use the keys and DeviceId from apple/google/MS and they know how to send the notification to the device.

**Comment by ppoetsma** [comment]
That's what I assumed but just checking. Thank you for the quick response Pim.
