### ISSUE TITLE
move to newer plugin?

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/MxPushNotifications#18]
This plugin is not maintained longer
https://github.com/phonegap-build/PushPlugin

A way more active plugin can be found here
https://github.com/phonegap/phonegap-plugin-push/releases

Should we invest some time, to swithc?

**Comment by simo101** [comment]
Agree. I was planning to do this. Just needed some time to spend on implementing this.

**Comment by simo101** [comment]
I have developed the first version of this. Will commit to the mainline tomorrow and adjust the readme. I have also removed the jquery. The code is much simpler now using the new phonegap plugin. I have tested it on Android, but need to test on iOS. Stay tuned for new update which should improve the widget.

**Comment by Andries-Smit** [comment]
Thank you. I will do some testing tomorrow, both iOS and Android. Cheers

**Comment by simo101** [comment]
I am currently working on this branch line: https://github.com/mendix/MxPushNotifications/tree/update-push-plugin

**Comment by simo101** [comment]
Apparently the plugin only works with phonegap cli 6.0.0 and above for iOS. So i had to change the config xml to: `<preference name="phonegap-version" value="cli-6.0.0" />`. I then had to change the required plugins to remove the versions. I have uploaded an example config file to the branch line.

**Comment by simo101** [comment]
@RCatersels @pimvdnoll @simonmartyr @Andries-Smit. As you have all contributed to this module in some way, would you mind testing this newer branch line I created. It uses the latest phonegap push plugin, which has simplified the Javascript and has made implementation easier. If tests pass I will look to push to the mainline.

**Comment by pimvdnoll** [comment]
what are the main new features/improvements in the new push plugin? I got it stable for a year now in a production app.

**Comment by simo101** [comment]
@pimvdnoll as mentioned above by andries the plugin that are currently using is deprecated. The new plugin is here: https://github.com/phonegap/phonegap-plugin-push/. In terms of new features for the plugin I am not 100% on all of them. One of the main ones I noticed is that it now supports Google Push notifications for IOS. I also noticed that the implementation of the plugin has been significantly been improved. If we continue using the old plugin we run the risk that future mobile versions won't be supported. I also seem to have several issues with it occasionally not registering on iOS. You don't need to use the new one if you are happy with the current implementation.

**Comment by simonmartyr** [comment]
Plan to test it out this Thursday.

**Comment by RCatersels** [comment]
I will take a look at it. I was working with mobile this week anyway so I will give the new module a try.

**Comment by simo101** [comment]
Thanks guys. My only concern at the moment is i had to upgrade the phonegap version to `<preference name="phonegap-version" value="cli-6.0.0" />` and i don't know what impact this will have on existing widgets. I also haven't been able to test on windows either so @simonmartyr if you are able to test it on windows this would help me.

**Comment by Andries-Smit** [comment]
Moving to CLI 6 you also minimal version of andriod 5.1

```
PhoneGap (iOS / Android / Windows)
cli-5.2.0 (3.9.1 / 4.1.1 / 3.8.1)
```

```
PhoneGap (iOS / Android / Windows)
cli-6.0.0 (4.0.1 / 5.1.0 / 4.3.0)
```

**Comment by simo101** [comment]
What's everyone's opinion on moving to this new plugin? I think there are some advantages and some disadvantages. I would like to see whether your ideas match my current thinking.

**Comment by dlhartveld** [comment]
Many people are still using Android 4.x - if we would upgrade to CLI 6, you exclude that target audience.

**Comment by pimvdnoll** [comment]
We have also 25%+ android 4.x users according to our google playstore statistics so I won't upgrade till  this percentage is lower

**Comment by simo101** [comment]
I did try it with cli 5.2.0 and the new plugin did build/work on Android. However iOS failed to build correctly, which was strange. There was some information on the issues, but on the support section it doesn't mention a minimum iOS version, so it should work. I agree we should only use this if we can work out how to support both iOS and Android 4+.

**Comment by Andries-Smit** [comment]
Documentation state:
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md

> This requires phonegap/cordova CLI 5.0+ ( current stable v1.6.3 )

If I have the spare moment, I will do some additional testing.

**Comment by Andries-Smit** [comment]
New branche will work with CLI 5.2, however phone gap build tries to make the build compatible with iOS 3.9.1

However the new plugin require it to at least on version 4.0: Build log file:

> Plugin doesn't support this project's cordova-ios version. cordova-ios: 3.9.1, failed version requirement: >=4.0.0
> Skipping 'phonegap-plugin-push' for ios

There is a way to make your build for iOS 4 and up with the following config.xml setting:

```<preference name="deployment-target" value="7.0" />```

however in de build process it will keep skipping the notification plugin, because this setting affects the ipa file and not the build settings of phone gap.

**Comment by pimvdnoll** [comment]
caution with  upgrading the plugin  in the config.xml: 

	<gap:plugin name="phonegap-plugin-push" source="npm" version="1.9.2" />

will  NOT work. We sticked to 1.5.3

**Comment by KevinVlaanderen** [comment]
Hi Pim,

Can you elaborate on your attempt to upgrade to version 1.9.2? What problems are you running into?
Since 1.5.3, there were a few breaking changes, such as the fact that the SenderID needs to be specified in the config.xml (as I understood it). This means that, without changes to the pushNotifications widget, 1.9.2 will indeed not work.
Is this what you are referring to, or are there more?

We are currently re-considering updating MxPushNotifications (module+widget) to be compatible with 1.8.x or 1.9.x. This would also help dealing with e.g. the entitlement issue.

**Comment by KevinVlaanderen** [comment]
About this overview:

```
PhoneGap (iOS / Android / Windows)
cli-5.2.0 (3.9.1 / 4.1.1 / 3.8.1)
PhoneGap (iOS / Android / Windows)
cli-6.0.0 (4.0.1 / 5.1.0 / 4.3.0)
```

It seems the conclusion was drawn that upgrading the CLI to version 6.x would increase the requirement on the Android platform to 5.x. However, this is not quite correct. The requirement is on the Cordova Android platform ([see overview](https://build.phonegap.com/current-support)).

Cordova Android 5.1.x supports Android API level 14--23, which means 4.0.1 (Ice Cream Sandwich) to 6.0 (Marshmallow).

Upgrading to Phonegap CLI 6.3.0/1 would require Cordova Android 5.2.1/2, with support for the same Android API levels.

Upgrading to Phonegap CLI 6.4.0 would require Cordova Android 6.1.0, with support for API levels 16--24, which means 4.1.x (Jelly Bean) to 7.0 (Nougat).

* disclaimer: these are the versions that Phonegap Build uses; actual requirements might be slightly lower.


For iOS, either Cordova iOS 4.2.x or 4.3.x is required; they all support iOS 8+. The [push plugin docs](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PHONEGAP_BUILD.md) state that Phonegap Build currently does not support v1.9.x, but when I tried building an app with CLI 6.4.0 and push plugin 1.9


As for the push plugin, 1.9.x requires CLI 6.4.0 and 1.8.x requires CLI 3.6.3 (!).



Please let me know if you feel this overview is incorrect.


Sources:
[Cordova iOS](https://cordova.apache.org/docs/en/latest/guide/platforms/ios/)
[Cordova Android](https://cordova.apache.org/docs/en/latest/guide/platforms/android/)
[PhoneGap Build support](https://build.phonegap.com/current-support)
[Push plugin support](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PLATFORM_SUPPORT.md)

**Comment by pimvdnoll** [comment]
thnx @KevinVlaanderen for the overview. We will build the ipa with the new versions config.
