### ISSUE TITLE
remove use of jquery

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/MxPushNotifications#19]
Mendix is already heavy loading on mobile.
The jquery library is only used for hide and show some div. loading 250kb(not minified)  for such simple function could be avoided using dojo instead.

**Comment by simo101** [comment]
Agree. Something we could replace with dojo functionality.

**Comment by simo101** [comment]
Will be in the next release.

**Comment by KevinVlaanderen** [comment]
This issue was solved with release 1.0.0
