### ISSUE TITLE
Loading new module fails

### ISSUE THREAD

**Issue by RCatersels** [mendix/MxPushNotifications#2]
When I now try to import the module it just fails without a specific error. Only the message Loading the module fails. From the version number I do see no change (still 1.0), but normally a module would overwrite the existing module even if it was the same version. 
I did extract the module and I can not see any fault in the structure. Strange.

Regards,

Ronald

**Comment by simo101** [comment]
Ok thanks Ronald. Very strange I will look into this now.

**Comment by simo101** [comment]
Hi Ronald. I got 5 errors once the module was imported. These were down to layouts inheriting no existent layouts, encryption module and non existent images. I will fix the layouts and images issue, however I am unable to replicate your error. There should be a new version in the module folder called 1.2. I will release a new version now called 1.3 to try to improve the import procedure. Which business modeller version are you using?

**Comment by simo101** [comment]
I have uploaded a new module now. Let me know if this improves the issue.

**Comment by simo101** [comment]
This issue was due to the module being imported into a 5.13.1 project when the module is from Mendix 5.14.1
