### ISSUE TITLE
Apple tokens (device id) are logged

### ISSUE THREAD

**Issue by ppoetsma** [mendix/MxPushNotifications#24]
Hi,

The module logs Apple tokens (or so called device id) as Info in the application log. This is a security risk therefore please remove this from the code. I did not look at Windows and Android.

Regards,
Paul

**Comment by simo101** [comment]
Fixed in latest release 3.1.

**Comment by ppoetsma** [comment]
Does your change include (or exclude, depends on how you look at it) logging tokens from Java as well?

**Comment by simo101** [comment]
I just implemented this on the JavaScript widget layer. As this is more of a security risk. Someone would have to gain access to the application server to see the logging on the Java. If this managed to happen, logging of registration ID's would be the least of your problems.
