### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by JelteMX** [mendix/MxPushNotifications#30]
Can you make sure the version number in package.xml stays the same as the release tag? That way it's easier to find out later on what version someone is using.

(You can set version numbers by using the version task in Grunt: ``grunt version`` will tell you the current version number, you can set it by using ``grunt version:x.y.z``)

**Comment by reinouts** [comment]
hey @JelteMX , thanks for pointing this out. Once we have the upgrade to the new phonegap push plugin in place we'll change the id of the widget and bring the numbering in sync again. As the Modeler won't upgrade to a newer version of the widget if you lower the release number we kept it as it was for now.
