### ISSUE TITLE
Microflow Action "Queue Message" never commits message

### ISSUE THREAD

**Issue by tieniber** [mendix/MxPushNotifications#38]
I tried to use the Microflow action "Queue Message", which calls a microflow "CreateAndQueueMessage". Unfortunately, this flow never actually commits the message, so it doesn't get picked up by the scheduled task which retrieves from the database.

I believe adding a "Commit Message" task to the end of "CreateAndQueueMessage" should do the trick. Please let me know if I'm missing something.

**Comment by KevinVlaanderen** [comment]
We'll fix this issue in the next release (probably end of this week)

**Comment by KevinVlaanderen** [comment]
This issue is now fixed, with release 2.0.0
