### ISSUE TITLE
Documentation could be clearer on two points.

### ISSUE THREAD

**Issue by RCatersels** [mendix/MxPushNotifications#4]
I have got the module working. I have gone off track on two occasions. The first one is when doing the certificates. The problem is not specific this module, but after creating the Phonegap app you have multiple security certificates (iOS Development and APN Development iOS) and I ended up mixing some up. The point is that the whole process can be quite overwhelming when you do it for the first time and you explanation with the screenshots is better that the how to on phonegap.

The second point I did got of track was at this point in the documentation:
"The push notification snippet must be included on all layouts for mobile and tablet."
I should have done what is said here, but I just copied the widget on those location and I should have copied it from your demo layouts to our own layouts. When you only place the widget on the form you get irratic behaviour of the application. So the text is right but one can easily make a mistake here. 

Regards,

Ronald

**Comment by dlhartveld** [comment]
@RCatersels, we think your remarks should be resolved with the recent documentation update. Can you confirm this?

**Comment by RCatersels** [comment]
Yes, this one is resolved in the current documentation.
