### ISSUE TITLE
I am missing the module package (or have I overlooked it somewhere?).

### ISSUE THREAD

**Issue by RCatersels** [mendix/MxPushNotifications#49]
I receive an error when I try to download the latest module from the appstore. So I downloaded this repository but can not find it here either. I could offcourse export the module from the demo project but I see that the version number is still on 2.2.0 while according to the appstore the latest is 2.2.1.
Could somebody fix the appstore download or either tell me if the demo projects has the latest 2.2.1 version and only the version number is off in this module.

Regards,

Ronald

**Comment by KevinVlaanderen** [comment]
Hi Ronald,

I'll look into it this morning.

Kevin

**Comment by KevinVlaanderen** [comment]
Should be fixed now. I published v2.2.2. No functional changes, but AppStore uploads always need an incremented version number :)

**Comment by RCatersels** [comment]
Thank you for the quick fix.
