### ISSUE TITLE
Error thrown on loading the widget

### ISSUE THREAD

**Issue by simo101** [mendix/MxPushNotifications#64]
Currently the widget throws a javascript error when loading the widget. The problem is because on this line we are using a variable that is undefined. So when it tries to use get it will throw an js error and also you'll get a mendix popup in the app. Please either remove this log line or just change it so that it is accessible.

[https://github.com/mendix/MxPushNotifications/blob/master/src/pushNotifications/widget/pushNotifications.js#L305
](https://github.com/mendix/MxPushNotifications/blob/master/src/pushNotifications/widget/pushNotifications.js#L305
)

**Comment by KevinVlaanderen** [comment]
Fixed by 9f03fe00af3f72dc4e16c99145558e729ba82599
