### ISSUE TITLE
When the afterstartup is missing you get java compile errors.

### ISSUE THREAD

**Issue by RCatersels** [mendix/MxPushNotifications#7]
One for the documentation. When you add the pushnotification library but forget to include the afterstartup microflow you get Java compile errors. 

Regards,

Ronald

**Comment by simo101** [comment]
Ok I will try to look into this.

**Comment by RCatersels** [comment]
The problem is something deeper. We get the error in line 59:
Cannot make a static reference to the non-static method addExtensionProvider(String, String, Object) from the type ProviderManager	GCMConnection.java	/Master Daywize-main/javasource/pushnotifications/implementation/gcm	line 59	Java Problem

Now the strange part. When I have Eclipse open the model will run. But as soon as I close Eclipse the model will not run anymore with the above error.

**Comment by simo101** [comment]
I tried to replicate this but i couldn't do this. I deselected the after startup flow and then restarted the test app and it didn't cause an issue.

**Comment by simo101** [comment]
Unable to replicate.
