### ISSUE TITLE
Could not find GCM settings Object

### ISSUE THREAD

**Issue by dan-lawford** [mendix/MxPushNotifications#72]
Hi, 

I am having issues with the widget I have followed the user guide on how to implement (https://docs.mendix.com/howto/mobile/implementation-guide) however we have found that when the app starts the user is not getting asked to give permission for notifications and as a result their device does not get registered. Notifications are enable and we have the after start up microflow and snippet in our layout

The only thing we can see in the device console is the following error saying 'Could not find GCM settings object'. It seems the widget cannot find the GCM settings entity but I'm unsure why. 
![screen shot 2018-10-12 at 14 50 36](https://user-images.githubusercontent.com/12201009/46939914-659c1b00-d05f-11e8-9eb0-06afb9e5be9b.png)

We are using Mendix version 7.15.1, I notice that on the information it states the widget is compatible with versions 6.8.1or higher.

**Comment by KevinVlaanderen** [comment]
Hi Dan,

It sounds like you're running into a known issue in the widget. It requires a GCM profile to be configured and active, on the push notifications configuration screen. It can contain bogus information, but it does have to be there.

We'll fix this in a future release.

Cheers,
Kevin

**Comment by dan-lawford** [comment]
Hi Kevin, 

Unfortunately we have the config set up and enabled for both APN and GCM(Firebase) already. 

Regards,

Dan
