### ISSUE TITLE
Release 3.0.0 is not compatible with Modeler 7.5.0

### ISSUE THREAD

**Issue by rcha103** [mendix/MxPushNotifications#74]
My client has a Mendix app (developed using Mendix 7.5.0) which employs push notifications through the Mendix Push Notifications module. So when I saw the module update version 3.0.0, my intention is to update the client's app to be compatible with the breaking changes. However, in the app store page, it is not possible to download the module update. 

![untitled](https://user-images.githubusercontent.com/25000946/50749504-38d05c00-127a-11e9-8e10-539db297f33b.png)

Can the module be updated ASAP for this issue? Thanks!

**Comment by KevinVlaanderen** [comment]
Good morning Rionald. I'm looking into the issue. Thank you for reporting.

**Comment by KevinVlaanderen** [comment]
We re-published the Push Notifications module with a lower Mendix version (6.10.3). You should be able to import this version using any Mx7 modeler.

**Comment by rcha103** [comment]
Thanks @KevinVlaanderen , I can now download the module. One more question, when will the documentation page for Mendix Push Notifications get updated? The configurations shown on the documentation page are completely different with version 3.

**Comment by KevinVlaanderen** [comment]
Good to hear. We'll release updated documentation this week.

**Comment by KevinVlaanderen** [comment]
The updated documentation can be found [here](https://docs.mendix.com/howto/mobile/push-notifications )
