### ISSUE TITLE
FCMPrivateKey object is always empty over retrieve

### ISSUE THREAD

**Issue by Mcpoowl** [mendix/MxPushNotifications#75]
I've been upgrading my project with the latest push notifications, and after figuring out what Private Key to upload for FCM, I breakpointed the IVK_SaveFCMSettings microflow, and no matter what, $FCMPrivateKey is always empty, even when I upload the actual file. It might even be a bug in the modeler? 

The object IS created, as I can actually select a file in the DS_GetOrCreateFCMPrivateKey dataview, so there's something amiss in the retrieve over association I presume.

My user has the Administrator role.

Modeler is 7.18.1

![image](https://user-images.githubusercontent.com/2244753/50963866-23537000-14ce-11e9-9cb9-56c885c2098b.png)

**Comment by Mcpoowl** [comment]
For some reason, putting that retrieve in a sub microflow fixed the issue. Still seems weird though..

**Comment by MulderWH** [comment]
@Mcpoowl fyi the retrieve is working fine in mx 7.20

**Comment by Mcpoowl** [comment]
> @Mcpoowl fyi the retrieve is working fine in mx 7.20

Weird, I've tried upgrading to 7.22.1 as well, but the retrieve was always empty there aswell. Might be a project specific issue, although a colleague of mine experienced the same. Thanks for the headsup!

**Comment by Mcpoowl** [comment]
Fixed due to upgrade for some reason
