### ISSUE TITLE
Error in Internet Explorer IE11

### ISSUE THREAD

**Issue by OlafJoppe** [mendix/MxPushNotifications#76]
I have implemented the MxPushNotifications module in a new project (Mx 7.22.2). Even before configuring the settings and testing my push notifications I noticed a small bug in the accompanying widget that is only reported by Internet Explorer (using latest IE11).

The error is on line 231 of the pushNotifications.js file and states that an illegal character is used. When changing the inverted comma and repackaging the widget, the error disappears.

**Comment by tieniber** [comment]
+1, have also encountered this issue with a client. On this line, a template literal (backtick) is used, which is not supported in IE11

**Comment by tieniber** [comment]
Possible fix here: https://github.com/tieniber/MxPushNotifications/commit/ef6012ccdb892f73543e1fc4c2dad65426744373

Will submit a PR if testing is successful.

**Comment by BlokJan** [comment]
There are typos in the file pushNotifications.js of the widget causing all kinds of widgets not rendering in IE11.

When you replace this line (with strange quotes at the start and end and a missing semicolon after this)):
var card = `<div class="alert alert-info alert-dismissible animated fadeInDown" role="alert" onClick='window.pushWidget.onClickAlert(${JSON.stringify(data.additionalData)},this)'>` +

with

var card = '<div class="alert alert-info alert-dismissible animated fadeInDown" role="alert" onClick="window.pushWidget.onClickAlert(${JSON.stringify(data.additionalData)},this);">' +

the issues in IE are fixed.

**Comment by tieniber** [comment]
The weird quotes are backticks and are a real JS feature in newer browsers. Obviously doesn’t work with IE11. My commit is working successfully so I’ll submit a PR.

**Comment by Mcpoowl** [comment]
Just came here to mention I ran in to the same issue so I'd like to see #77 merged for future use.

**Comment by mmehmetAliIzci** [comment]
We fixed this issue with 4.0.6. Thus closing this issue now.

Please feel free to reopen another issue if this persists.
