### ISSUE TITLE
Possibility to enable multiple server settings

### ISSUE THREAD

**Issue by RCatersels** [mendix/MxPushNotifications#8]
Simon,
It seems that the groundwork for multiple settings have been made into the model but are not active. In an environment with test, accp and a production environment it would be very nice if you could create all three setups and make the right one active depending on the environment. 

I do not know if it is related, but we encounter all kind of weird Java compile errors when changing the environment from let's say acceptance to production. Suddenly the server will not start anymore and throw the errors as seen in issue 2. Since we also did a database restore it could be it is starting the accp setting in production that will probably not work because url etc are all wrong. I have to test some more what is causing these (timeout?) problems. 

Regards,

Ronald

**Comment by simo101** [comment]
Hi Ronald. You can set up different settings as it's just data in an entity. So you could have different settings for production, test and acceptance. Surely you would just want one setting per server? Does your pull request fix this issues that you were having? If so ill incorporate your change and close off the issue.

**Comment by simo101** [comment]
I have merged your pull request into the application.

**Comment by simo101** [comment]
Ronald I just tested your app changes and the after startup flow is currently creating new objects for me everytime now.

**Comment by simo101** [comment]
I have made some adjustments to the after startup flow and also some changes to the security model. Hopefully this will improve the issue. I will also test on and actual Acceptance/Production environment.
